package Main.Accounts;

//This class is a singular user, containing his/her name, password hash and the ugly URL, and the flair.
public class User {
    private String name;
    private String passHash; //No password is ever stored with this method.
    private String uURL;
    private String flair; //This value allows one to change the key/tinyURL that is generated as they are generated by hashing the string made from the user. Thus changing the string changes the hash.
    private String defaultFlair = "00000000";

    public User(String Name, String passhash, String ugly){
        //System.out.println("Creating user for " + Name + "!");

        this.name = Name;
        this.passHash = passhash;
        this.uURL = ugly;
        this.flair = defaultFlair;
    }

    public User(String Name, String passhash, String ugly, String flair){
        //System.out.println("Creating user for " + Name + "!");

        this.name = Name;
        this.passHash = passhash;
        this.uURL = ugly;
        this.flair = flair;
    }

    // {Name, password hash, nice URL, ugly URL}
    public String makeString(){
        return "{" + this.name + "," + this.passHash + "," + this.uURL + "," + this.flair + "} \n" ;
    }

    //A function to make the user entry into a postable String.
    public void printUser(){
        System.out.println(this.makeString());
    }

    public String getName(){
        return this.name;
    }

    public String getPassHash(){
        return this.passHash;
    }

    public String getuURL(){
        return this.uURL;
    }
}
